/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { DefaultHooks } from '../types';

export type ProductCategory = {
  _id?: string; // {"type":"string","required":false,"default":""}
  label?: string; // {"type":"string","required":false,"default":""}
};

export type Product = {
  _id?: string; // {"type":"string","required":false,"format":"uuid","default":""}
  created?: string; // {"type":"string","required":false,"default":""}
  updated?: string; // {"type":"string","required":false,"default":""}
  createdBy?: string; // {"type":"string","required":false,"default":""}
  updatedBy?: string; // {"type":"string","required":false,"default":""}
  tenantId?: number; // {"type":"number","required":false,"default":1}
  orgId?: number; // {"type":"number","required":false,"default":1}
  branchId?: number; // {"type":"number","required":false,"default":1}
  productCode?: string; // {"type":"string","required":false,"examples":["BK-MTHP1"],"default":""}
  productName?: string; // {"type":"string","required":false,"examples":["Math Primary 1 Book"],"default":""}
  defaultPrice?: number; // {"type":"number","required":false,"default":0}
  active?: boolean; // {"type":"boolean","required":false,"default":true}
  description?: string; // {"type":"string","required":false,"default":""}
  tags: string[]; //array

  category: ProductCategory; //child object
};

export type ProductHooks = DefaultHooks<Product> & {};
