/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-04-15
 * Author: Ks Tan
 */

export type WorkflowCatalogue = {
  sayhello: any;
};

export type WorkflowName = keyof WorkflowCatalogue;
