/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
export enum Role {
  Unknown = 'unknown', // unuse yet
  Everyone = 'everyone', //everyone
  SuperAdmin = 'superadmin', //reserved for developers, no control,
  SuperUser = 'suerpuser', //reserved, plan use by support
  TenantOwner = 'tenantowner', //tenant owner/creator
  User = 'user',
  Tenant_create = 'Tenant:create',

  Tenant_update = 'Tenant:update',

  Tenant_delete = 'Tenant:delete',

  Tenant_search = 'Tenant:search',

  Organization_create = 'Organization:create',

  Organization_update = 'Organization:update',

  Organization_delete = 'Organization:delete',

  Organization_search = 'Organization:search',

  Branch_create = 'Branch:create',

  Branch_update = 'Branch:update',

  Branch_delete = 'Branch:delete',

  Branch_search = 'Branch:search',

  Permission_create = 'Permission:create',

  Permission_update = 'Permission:update',

  Permission_delete = 'Permission:delete',

  Permission_search = 'Permission:search',

  Permission_listUser = 'Permission:listUser',

  Autoincreament_create = 'Autoincreament:create',

  Autoincreament_update = 'Autoincreament:update',

  Autoincreament_delete = 'Autoincreament:delete',

  Autoincreament_search = 'Autoincreament:search',

  Autoincreament_generateNextNo = 'Autoincreament:generateNextNo',

  Docnoformat_create = 'Docnoformat:create',

  Docnoformat_update = 'Docnoformat:update',

  Docnoformat_delete = 'Docnoformat:delete',

  Docnoformat_search = 'Docnoformat:search',

  Docnoformat_listDocFormats = 'Docnoformat:listDocFormats',

  Category_create = 'Category:create',

  Category_update = 'Category:update',

  Category_delete = 'Category:delete',

  Category_search = 'Category:search',

  Customer_create = 'Customer:create',

  Customer_update = 'Customer:update',

  Customer_delete = 'Customer:delete',

  Customer_search = 'Customer:search',

  Invoice_create = 'Invoice:create',

  Invoice_update = 'Invoice:update',

  Invoice_delete = 'Invoice:delete',

  Invoice_search = 'Invoice:search',

  Product_create = 'Product:create',

  Product_update = 'Product:update',

  Product_delete = 'Product:delete',

  Product_search = 'Product:search',

  User_create = 'User:create',

  User_update = 'User:update',

  User_delete = 'User:delete',

  User_search = 'User:search',
}
