/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
import { Role } from './roles.enum';

export const admin = () => [
  Role.User,
  Role.Autoincreament_create,
  Role.Autoincreament_update,
  Role.Autoincreament_delete,
  Role.Autoincreament_search,
  Role.Autoincreament_generateNextNo,
  Role.Branch_create,
  Role.Branch_update,
  Role.Branch_delete,
  Role.Branch_search,
  Role.Organization_create,
  Role.Organization_update,
  Role.Organization_search,
  Role.Organization_delete,
  Role.Permission_listUser,
  Role.Permission_search,
  Role.Permission_delete,
  Role.Permission_update,
  Role.Permission_create,
  Role.Tenant_create,
  Role.Tenant_update,
  Role.Tenant_delete,
  Role.Tenant_search,
  Role.User_create,
  Role.User_update,
  Role.User_search,
  Role.User_delete,
];
