/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { AutoincreamentProcessor } from '../generate/processors/autoinc.processor';

import { Autoincreament,AutoincreamentHooks } from '../generate/types';
import { UserContext } from '../generate/commons/user.context';
export { Autoincreament } from '../generate/types';

@Injectable()
export class AutoincreamentService extends AutoincreamentProcessor {
  hooks: AutoincreamentHooks = {};
  constructor(@InjectModel('Autoincreament') mydoc: Model<Autoincreament>) {
    super(mydoc);
  }


  async runGenerateNextNo(
    appuser: UserContext,
    collection: string,
    field: string,
  ) {
    const res = await this.search(appuser, {
      collectionName: collection,
      fieldName: field,
    });
    // console.log(res)
    let data;
    if (res.length > 0) {
      // console.log("FOUND RESULT------")
      const tmp = res[0];
      const nextno = tmp.nextNo;
      data = { collectionName: collection, fieldName: field, nextno: nextno };
      this.findIdThenUpdate(appuser, tmp._id, {
        collectionName: collection,
        fieldName: field,
        nextNo: tmp.nextNo + 1,
      });
    } else {
      // console.log("CREATE ROW------")
      this.data = { collectionName: collection, fieldName: field, nextNo: 2 };
      const createResult = await this.create(appuser, this.data);
      data = {
        _id: crypto.randomUUID(),
        collectionName: collection,
        fieldName: field,
        nextno: 1,
      };
    }

    return data;
  }
}
