/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { OrganizationProcessor } from '../generate/processors/org.processor';
import { Organization,OrganizationHooks } from '../generate/types';
export { Organization } from '../generate/types';
import { AutoincreamentService } from './autoinc.service';
import { UserContext } from '../generate/commons/user.context';

@Injectable()
export class OrganizationService extends OrganizationProcessor {
  protected strictIsolation = false;
  protected hooks : OrganizationHooks = {
    beforeCreate: async (appuser: UserContext, data: Organization) => await this.orgBeforeCreate(appuser,data),
  };
  constructor(
    @InjectModel('Organization') mydoc: Model<Organization>,
    private increament: AutoincreamentService,
  ) {
    super(mydoc);
  }

  async orgBeforeCreate(appuser:UserContext,data:Organization){
    const searchresult = await this.increament.runGenerateNextNo(
          appuser,
          'organization',
          'orgId',
        );
        data.orgId = searchresult.nextno;
  }  
}
