/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import {DocNumberFormatGenerator} from './generate/commons/docnogenerator.service'
import { AuditTrail } from './generate/commons/audittrail.service';

// auto import modules
import { TenantService } from './services/tenant.service';    
import { TenantController } from './generate/controllers/tenant.controller';    
import { TenantMongoSchema } from './generate/models/tenant.model';
import { OrganizationService } from './services/org.service';    
import { OrganizationController } from './generate/controllers/org.controller';    
import { OrganizationMongoSchema } from './generate/models/org.model';
import { BranchService } from './services/branch.service';    
import { BranchController } from './generate/controllers/branch.controller';    
import { BranchMongoSchema } from './generate/models/branch.model';
import { PermissionService } from './services/perm.service';    
import { PermissionController } from './generate/controllers/perm.controller';    
import { PermissionMongoSchema } from './generate/models/perm.model';
import { AutoincreamentService } from './services/autoinc.service';    
import { AutoincreamentController } from './generate/controllers/autoinc.controller';    
import { AutoincreamentMongoSchema } from './generate/models/autoinc.model';
import { DocnoformatService } from './services/docno.service';    
import { DocnoformatController } from './generate/controllers/docno.controller';    
import { DocnoformatMongoSchema } from './generate/models/docno.model';
import { CategoryService } from './services/cat.service';    
import { CategoryController } from './generate/controllers/cat.controller';    
import { CategoryMongoSchema } from './generate/models/cat.model';
import { CustomerService } from './services/cust.service';    
import { CustomerController } from './generate/controllers/cust.controller';    
import { CustomerMongoSchema } from './generate/models/cust.model';
import { InvoiceService } from './services/inv.service';    
import { InvoiceController } from './generate/controllers/inv.controller';    
import { InvoiceMongoSchema } from './generate/models/inv.model';
import { ProductService } from './services/prd.service';    
import { ProductController } from './generate/controllers/prd.controller';    
import { ProductMongoSchema } from './generate/models/prd.model';
import { UserService } from './services/user.service';    
import { UserController } from './generate/controllers/user.controller';    
import { UserMongoSchema } from './generate/models/user.model';
import { ProfileController } from './profile/profile.controller';
import { ProfileService } from './profile/profile.service';
import { WorkflowController } from './generate/workflow/workflow.controller';
import { WorkflowDelegate } from './generate/workflow/workflow.delegate';
import { WorkflowConfig } from './generate/workflow/workflow.config';
import { WorkflowService } from './generate/workflow/workflow.service';
import { WorkflowUserService } from './generate/workflow/workflow.userservice';
import { SayhelloListenerService } from 'src/simpleapp/workflows/listeners/sayhello.listener';
// import {ServiceModule} from  "../services/service.module"
//import { undefinedService } from '../../generate/undefined/undefined.service';


//import {AutoincreamentModule} from '../autoinc/autoinc.module'//encryption use for model (not class and cant inject, use singleton instead and init as early as possible)

@Module({
  imports: [
   MongooseModule.forFeature([
                            { name: 'Tenant', schema: TenantMongoSchema },
                            { name: 'Organization', schema: OrganizationMongoSchema },
                            { name: 'Branch', schema: BranchMongoSchema },
                            { name: 'Permission', schema: PermissionMongoSchema },
                            { name: 'Autoincreament', schema: AutoincreamentMongoSchema },
                            { name: 'Docnoformat', schema: DocnoformatMongoSchema },
                            { name: 'Category', schema: CategoryMongoSchema },
                            { name: 'Customer', schema: CustomerMongoSchema },
                            { name: 'Invoice', schema: InvoiceMongoSchema },
                            { name: 'Product', schema: ProductMongoSchema },
                            { name: 'User', schema: UserMongoSchema },
              ]),
  ],
  controllers: [TenantController,OrganizationController,BranchController,PermissionController,AutoincreamentController,DocnoformatController,CategoryController,CustomerController,InvoiceController,ProductController,UserController, ProfileController,WorkflowController],
  providers: [
    AuditTrail,DocNumberFormatGenerator,TenantService,OrganizationService,BranchService,PermissionService,AutoincreamentService,DocnoformatService,CategoryService,CustomerService,InvoiceService,ProductService,UserService, ProfileService,WorkflowDelegate,WorkflowConfig,WorkflowService,WorkflowUserService,
                     SayhelloListenerService,
      ],
  exports:[AuditTrail,DocNumberFormatGenerator,TenantService,OrganizationService,BranchService,PermissionService,AutoincreamentService,DocnoformatService,CategoryService,CustomerService,InvoiceService,ProductService,UserService, ProfileService,WorkflowDelegate,WorkflowConfig,WorkflowService,WorkflowUserService,]
})
export class GenerateModule {}
