/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
import { ApiProperty } from '@nestjs/swagger';
export class ForeignKey {
  @ApiProperty({ type: 'string', required: false, format: 'uuid', default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  code: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  label: string;
}

export class UserAllPermissionsBranches {
  @ApiProperty({ type: 'string', required: true, default: '' })
  permId: string;
  @ApiProperty({ type: Number, required: true, default: 0 })
  branchId: number;
  @ApiProperty({ type: () => ForeignKey, required: true })
  branch: ForeignKey;

  groups: string[];
  @ApiProperty({ type: 'string', required: true, default: '' })
  userId: string;
}

export class UserPermission {
  @ApiProperty({ type: 'string', required: true, format: 'uuid', default: '' })
  permId: string;
  @ApiProperty({ type: Number, required: true, default: 0 })
  branchId: number;
  @ApiProperty({ type: () => ForeignKey, required: true })
  branch: ForeignKey;

  @ApiProperty({ type: [String], required: true, default: '' })
  groups: string[];
  @ApiProperty({ type: 'string', required: true, format: 'uuid', default: '' })
  userId: string;
}
