/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { ApiProperty } from '@nestjs/swagger';

export class Category {
  @ApiProperty({ type: 'string', required: false, format: 'uuid', default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  created: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updated: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  createdBy: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updatedBy: string;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  tenantId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  orgId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  branchId: number;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['TUITION'],
    default: '',
  })
  categoryCode: string;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['Tuition Service'],
    default: '',
  })
  categoryName: string;
  @ApiProperty({
    type: 'boolean',
    required: false,
    examples: [true],
    default: true,
  })
  active: boolean;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['class'],
    default: '',
  })
  categoryType: string;
  @ApiProperty({
    type: 'string',
    required: false,
    format: 'text',
    examples: ['Maths Tuition primary 1'],
    default: '',
  })
  description: string;
}

/*****************************customized code begin here *****************************************/
