/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { ApiProperty } from '@nestjs/swagger';

export class CustomerDocNoFormat {
  @ApiProperty({ type: 'string', required: false, default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  label: string;
}

export class Customer {
  @ApiProperty({ type: 'string', required: false, format: 'uuid', default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  created: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updated: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  createdBy: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updatedBy: string;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  tenantId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  orgId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  branchId: number;
  @ApiProperty({
    type: 'string',
    required: false,
    format: 'documentno',
    examples: ['S0001'],
    default: '',
  })
  customerNo: string;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['Customer 1'],
    default: '',
  })
  customerName: string;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['unknown'],
    default: '',
  })
  customerStatus: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  email: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  tel: string;
  @ApiProperty({
    type: 'boolean',
    required: false,
    examples: [true],
    default: true,
  })
  active: boolean;
  @ApiProperty({ type: 'string', required: false, format: 'text', default: '' })
  description: string;
  @ApiProperty({ type: () => CustomerDocNoFormat })
  docNoFormat: CustomerDocNoFormat;
}

/*****************************customized code begin here *****************************************/
