/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { ApiProperty } from '@nestjs/swagger';

export class DocnoformatBranch {
  @ApiProperty({ type: 'string', required: false, default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  label: string;
  @ApiProperty({ type: 'number', required: false, default: 0 })
  branchId: number;
}

export class Docnoformat {
  @ApiProperty({ type: 'string', required: false, format: 'uuid', default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  created: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updated: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  createdBy: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updatedBy: string;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  tenantId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  orgId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  branchId: number;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['INV'],
    default: '',
  })
  docNoFormatNo: string;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['Invoice Default Format'],
    default: '',
  })
  docNoFormatName: string;
  @ApiProperty({
    type: 'boolean',
    required: false,
    examples: [true],
    default: true,
  })
  active: boolean;
  @ApiProperty({
    type: 'boolean',
    required: false,
    examples: [true],
    default: true,
  })
  default: boolean;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['SI', 'PI'],
    default: '',
  })
  docNoType: string;
  @ApiProperty({
    type: 'string',
    required: false,
    description: '{date} format as ISO8601 symbol',
    examples: ['SI{YYMM}-<000>', 'PI-2023-<0000>'],
    default: '',
  })
  docNoPattern: string;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  nextNumber: number;
  @ApiProperty({ type: () => DocnoformatBranch })
  branch: DocnoformatBranch;
}

/*****************************customized code begin here *****************************************/
