/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */

export * from './tenant.apischema';

export * from './org.apischema';

export * from './branch.apischema';

export * from './perm.apischema';

export * from './autoinc.apischema';

export * from './docno.apischema';

export * from './cat.apischema';

export * from './cust.apischema';

export * from './inv.apischema';

export * from './prd.apischema';

export * from './user.apischema';

export * from './simpleapp.apischema';

export * from '../../apischemas';
