/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { ApiProperty } from '@nestjs/swagger';

export class InvoiceCustomer {
  @ApiProperty({ type: 'string', required: false, default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  label: string;
}

export class InvoiceDetailsProduct {
  @ApiProperty({ type: 'string', required: false, default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  label: string;
  @ApiProperty({ type: 'number', required: false, default: 0 })
  defaultPrice: number;
}

export class InvoiceDetails {
  @ApiProperty({ type: 'number', required: false, default: 1 })
  quantity: number;
  @ApiProperty({ type: 'number', required: false, default: 0 })
  unitPrice: number;
  @ApiProperty({ type: 'number', required: false, default: 0 })
  subTotal: number;
  @ApiProperty({
    type: 'string',
    required: false,
    description: 'iso8601 dataempty mean new record',
    default: '',
  })
  created: string;
  @ApiProperty({
    type: 'string',
    required: false,
    description: 'iso8601 or empty',
    default: '',
  })
  updated: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  createdBy: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updatedBy: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  _id: string;
  @ApiProperty({ type: () => InvoiceDetailsProduct })
  product: InvoiceDetailsProduct;
}

export class InvoiceDocNoFormat {
  @ApiProperty({ type: 'string', required: false, default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  label: string;
}

export class Invoice {
  @ApiProperty({ type: 'string', required: false, format: 'uuid', default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  created: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updated: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  createdBy: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updatedBy: string;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  tenantId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  orgId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  branchId: number;
  @ApiProperty({
    type: 'string',
    required: false,
    format: 'documentno',
    examples: ['SI1111'],
    default: '',
  })
  invoiceNo: string;
  @ApiProperty({ type: 'string', required: false, format: 'date', default: '' })
  invoiceDate: string;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['Sales to XYZ'],
    default: '',
  })
  invoiceTitle: string;
  @ApiProperty({ type: 'number', required: false, default: 0 })
  invoiceTotal: number;
  @ApiProperty({
    type: 'string',
    required: false,
    format: 'text',
    examples: ['Maths Tuition primary 1'],
    default: '',
  })
  description: string;
  @ApiProperty({ type: () => InvoiceCustomer })
  customer: InvoiceCustomer;
  @ApiProperty({ type: () => [InvoiceDetails] })
  details: InvoiceDetails[];

  @ApiProperty({ type: () => InvoiceDocNoFormat })
  docNoFormat: InvoiceDocNoFormat;
}

/*****************************customized code begin here *****************************************/
