/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { ApiProperty } from '@nestjs/swagger';

export class ProductCategory {
  @ApiProperty({ type: 'string', required: false, default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  label: string;
}

export class Product {
  @ApiProperty({ type: 'string', required: false, format: 'uuid', default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  created: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updated: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  createdBy: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updatedBy: string;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  tenantId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  orgId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  branchId: number;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['BK-MTHP1'],
    default: '',
  })
  productCode: string;
  @ApiProperty({
    type: 'string',
    required: false,
    examples: ['Math Primary 1 Book'],
    default: '',
  })
  productName: string;
  @ApiProperty({ type: 'number', required: false, default: 0 })
  defaultPrice: number;
  @ApiProperty({ type: 'boolean', required: false, default: true })
  active: boolean;
  @ApiProperty({ type: 'string', required: false, default: '' })
  description: string;
  @ApiProperty({ type: () => [String] })
  tags: string[];

  @ApiProperty({ type: () => ProductCategory })
  category: ProductCategory;
}

/*****************************customized code begin here *****************************************/
