/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { ApiProperty } from '@nestjs/swagger';

export class TenantOwner {
  @ApiProperty({ type: 'string', required: true, default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: true, default: '' })
  label: string;
  @ApiProperty({ type: 'string', required: true, default: '' })
  uid: string;
}

export class Tenant {
  @ApiProperty({ type: 'string', required: false, format: 'uuid', default: '' })
  _id: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  created: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updated: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  createdBy: string;
  @ApiProperty({ type: 'string', required: false, default: '' })
  updatedBy: string;
  @ApiProperty({ type: 'number', required: true, default: 1 })
  tenantId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  orgId: number;
  @ApiProperty({ type: 'number', required: false, default: 1 })
  branchId: number;
  @ApiProperty({ type: 'string', required: true, default: '' })
  tenantName: string;
  @ApiProperty({
    type: 'boolean',
    required: false,
    examples: [true],
    default: true,
  })
  active: boolean;
  @ApiProperty({ type: 'string', required: false, default: '' })
  description: string;
  @ApiProperty({ type: () => TenantOwner })
  owner: TenantOwner;
}

/*****************************customized code begin here *****************************************/
