/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */

    
export const DefaultDocnoformatBranch = (uuid:string)=>{
    // {"_id":{"type":"string","required":false,"default":""},"label":{"type":"string","required":false,"default":""},"branchId":{"type":"number","required":false,"default":0}}        
        return {
        _id : uuid,
              
                          
            
                    // skip cause already hardcoded
                        
                          
            
           
            label : '',
                        
                          
            
                      branchId : 0,  //it will override by save handle
                      }
  } 
    
export const DefaultDocnoformat = (uuid:string)=>{
    // {"_id":{"type":"string","required":false,"format":"uuid","default":""},"created":{"type":"string","required":false,"default":""},"updated":{"type":"string","required":false,"default":""},"createdBy":{"type":"string","required":false,"default":""},"updatedBy":{"type":"string","required":false,"default":""},"tenantId":{"type":"number","required":false,"default":1},"orgId":{"type":"number","required":false,"default":1},"branchId":{"type":"number","required":false,"default":1},"docNoFormatNo":{"type":"string","required":false,"examples":["INV"],"default":""},"docNoFormatName":{"type":"string","required":false,"examples":["Invoice Default Format"],"default":""},"active":{"type":"boolean","required":false,"examples":[true],"default":true},"default":{"type":"boolean","required":false,"examples":[true],"default":true},"docNoType":{"type":"string","required":false,"examples":["SI","PI"],"default":""},"docNoPattern":{"type":"string","required":false,"description":"{date} format as ISO8601 symbol","examples":["SI{YYMM}-<000>","PI-2023-<0000>"],"default":""},"nextNumber":{"type":"number","required":false,"default":1},"branch":"DocnoformatBranch"}        
        return {
        _id : uuid,
              
                          
            
                    // skip cause already hardcoded
                        
                          
            
           
            created : '',
                        
                          
            
           
            updated : '',
                        
                          
            
           
            createdBy : '',
                        
                          
            
           
            updatedBy : '',
                        
                          
            
                      tenantId : 0,//it will override by save handle
                        
                          
            
                      orgId : 0, //it will override by save handle
                        
                          
            
                      branchId : 0,  //it will override by save handle
                        
                          
            
           
            docNoFormatNo : '',
                        
                          
            
           
            docNoFormatName : '',
                        
                          
            
           
            active : true,
                        
                          
            
           
            default : true,
                        
                          
            
           
            docNoType : '',
                        
                          
            
           
            docNoPattern : '',
                        
                          
            
           
            nextNumber : 1,
                        
                          
            
                      branch :  DefaultDocnoformatBranch(''),
                      }
  } 
