/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */

export const DefaultPermission = (uuid: string) => {
  // {"_id":{"type":"string","required":false,"format":"uuid","default":""},"created":{"type":"string","required":false,"default":""},"updated":{"type":"string","required":false,"default":""},"createdBy":{"type":"string","required":false,"default":""},"updatedBy":{"type":"string","required":false,"default":""},"tenantId":{"type":"number","required":false,"default":1},"orgId":{"type":"number","required":false,"default":1},"branchId":{"type":"number","required":false,"default":1},"groups":["string"],"uid":{"type":"string","required":false,"description":"sso unique identity, which is keycloak sub","default":""},"userId":{"type":"string","required":false,"description":"primary key from user","format":"uuid","default":""}}
  return {
    _id: uuid,

    // skip cause already hardcoded

    created: '',

    updated: '',

    createdBy: '',

    updatedBy: '',

    tenantId: 0, //it will override by save handle

    orgId: 0, //it will override by save handle

    branchId: 0, //it will override by save handle

    groups: <string[]>[], //typeof field == array     ["string"]

    uid: '',

    userId: '',
  };
};
