/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
export type RegTenant = {
    tenantName: string;
  };
  export type ProfileUserBranch = {
    _id: string  
    branch: any  
    groups: string[]
    xOrg: string
  };
  export type ProfileUserInvites = {
    _id: string;
    email: string;
    fullName: string;
    tenantId: string;
    tenantName: string;
    created: string;
  };
  