/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
export const CategoryJsonSchema = {
  type: 'object',
  'x-simpleapp-config': {
    documentType: 'cat',
    documentName: 'category',
    isolationType: 'org',
    uniqueKey: 'categoryCode',
    documentTitle: 'categoryName',
    pageType: 'crud',
    foreignKeys: {},
  },
  properties: {
    _id: { type: 'string', format: 'uuid' },
    created: { type: 'string' },
    updated: { type: 'string' },
    createdBy: { type: 'string' },
    updatedBy: { type: 'string' },
    tenantId: { type: 'integer', default: 1 },
    orgId: { type: 'integer', default: 1 },
    branchId: { type: 'integer', default: 1 },
    categoryCode: { type: 'string', examples: ['TUITION'], minLength: 2 },
    categoryName: {
      type: 'string',
      examples: ['Tuition Service'],
      minLength: 3,
    },
    active: { type: 'boolean', default: true, examples: [true] },
    categoryType: {
      type: 'string',
      enum: ['class', 'charge', 'stock'],
      examples: ['class'],
    },
    description: {
      type: 'string',
      format: 'text',
      examples: ['Maths Tuition primary 1'],
    },
  },
};
