/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
export const CustomerJsonSchema = {
  type: 'object',
  'x-simpleapp-config': {
    documentType: 'cust',
    documentName: 'customer',
    uniqueKey: 'customerNo',
    documentTitle: 'customerName',
    generateDocumentNumber: true,
    isolationType: 'org',
    pageType: 'crud',
    foreignKeys: { docnoformat: ['$.docNoFormat._id'] },
  },
  properties: {
    _id: { type: 'string', format: 'uuid' },
    created: { type: 'string' },
    updated: { type: 'string' },
    createdBy: { type: 'string' },
    updatedBy: { type: 'string' },
    tenantId: { type: 'integer', default: 1 },
    orgId: { type: 'integer', default: 1 },
    branchId: { type: 'integer', default: 1 },
    customerNo: { type: 'string', format: 'documentno', examples: ['S0001'] },
    customerName: { type: 'string', examples: ['Customer 1'], minLength: 3 },
    customerStatus: {
      type: 'string',
      enum: ['unknown', 'potential', 'suspended', 'existing'],
      examples: ['unknown'],
    },
    email: { type: 'string', oneOf: [{ format: 'email' }, { enum: [''] }] },
    tel: { type: 'string', oneOf: [{ format: 'tel' }, { enum: [''] }] },
    active: { type: 'boolean', default: true, examples: [true] },
    description: { type: 'string', format: 'text' },
    docNoFormat: {
      type: 'object',
      'x-foreignkey': 'docnoformat',
      properties: { _id: { type: 'string' }, label: { type: 'string' } },
    },
  },
};
