/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
export const InvoiceJsonSchema = {
  type: 'object',
  'x-simpleapp-config': {
    documentType: 'inv',
    documentName: 'invoice',
    isolationType: 'org',
    uniqueKey: 'invoiceNo',
    documentTitle: 'invoiceTitle',
    documentDate: 'invoiceDate',
    generateDocumentNumber: true,
    pageType: 'crud',
    formulas: [
      { jsonPath: '$.details[*]', formula: 'sharelibs.getSubtotal(value)' },
      {
        jsonPath: '$.invoiceTotal',
        formula: 'sharelibs.getTotal(data.details)',
      },
    ],
    foreignKeys: {
      customer: ['$.customer._id'],
      product: ['$.details[*].product._id'],
      docnoformat: ['$.docNoFormat._id'],
    },
  },
  properties: {
    _id: { type: 'string', format: 'uuid' },
    created: { type: 'string' },
    updated: { type: 'string' },
    createdBy: { type: 'string' },
    updatedBy: { type: 'string' },
    tenantId: { type: 'integer', default: 1 },
    orgId: { type: 'integer', default: 1 },
    branchId: { type: 'integer', default: 1 },
    customer: {
      type: 'object',
      'x-foreignkey': 'customer',
      properties: { _id: { type: 'string' }, label: { type: 'string' } },
    },
    invoiceNo: { type: 'string', examples: ['SI1111'], format: 'documentno' },
    invoiceDate: { type: 'string', format: 'date' },
    invoiceTitle: { type: 'string', examples: ['Sales to XYZ'], minLength: 3 },
    invoiceTotal: { type: 'number', default: 0 },
    details: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          product: {
            type: 'object',
            'x-foreignkey': 'product',
            properties: {
              _id: { type: 'string' },
              label: { type: 'string' },
              defaultPrice: { type: 'number', default: 0 },
            },
          },
          quantity: { type: 'integer', default: 1 },
          unitPrice: { type: 'number', default: 0 },
          subTotal: { type: 'number', default: 0 },
          created: {
            type: 'string',
            description: 'iso8601 dataempty mean new record',
          },
          updated: { type: 'string', description: 'iso8601 or empty' },
          createdBy: { type: 'string' },
          updatedBy: { type: 'string' },
          _id: { type: 'string' },
        },
      },
    },
    description: {
      type: 'string',
      format: 'text',
      examples: ['Maths Tuition primary 1'],
    },
    docNoFormat: {
      type: 'object',
      'x-foreignkey': 'docnoformat',
      properties: { _id: { type: 'string' }, label: { type: 'string' } },
    },
  },
};
