/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
export const UserJsonSchema = {
  type: 'object',
  'x-simpleapp-config': {
    documentType: 'user',
    documentName: 'user',
    pageType: 'crud',
    isolationType: 'tenant',
    uniqueKey: 'email',
    loseDataIsolation: true,
    documentTitle: 'fullName',
    requiredRoles: ['SuperUser'],
    additionalAutoCompleteFields: ['uid'],
    foreignKeys: {},
  },
  properties: {
    _id: { type: 'string', format: 'uuid' },
    created: { type: 'string' },
    updated: { type: 'string' },
    createdBy: { type: 'string' },
    updatedBy: { type: 'string' },
    tenantId: { type: 'integer', default: 1, minimum: 0 },
    orgId: { type: 'integer', default: 1, minimum: 0 },
    branchId: { type: 'integer', default: 1, minimum: 0 },
    uid: { type: 'string' },
    fullName: { type: 'string', minLength: 3 },
    email: { type: 'string', minLength: 10, format: 'email' },
    active: { type: 'boolean', default: true },
    description: { type: 'string' },
    lastActivity: {
      type: 'string',
      description: 'capture ISO8601 last api call',
    },
  },
};
