/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
export const alldocuments: any[] = [
  {
    docName: 'Tenant',
    docType: 'TENANT',
    page: 'crud',
    isolationType: 'none',
    documentDate: '',
    docNumber: false,
  },

  {
    docName: 'Organization',
    docType: 'ORG',
    page: 'crud',
    isolationType: 'tenant',
    documentDate: '',
    docNumber: false,
  },

  {
    docName: 'Branch',
    docType: 'BRANCH',
    page: '',
    isolationType: 'org',
    documentDate: '',
    docNumber: false,
  },

  {
    docName: 'Permission',
    docType: 'PERM',
    page: '',
    isolationType: 'org',
    documentDate: '',
    docNumber: false,
  },

  {
    docName: 'Autoincreament',
    docType: 'AUTOINC',
    page: 'crud',
    isolationType: 'none',
    documentDate: '',
    docNumber: false,
  },

  {
    docName: 'Docnoformat',
    docType: 'DOCNO',
    page: 'crud',
    isolationType: 'org',
    documentDate: '',
    docNumber: false,
  },

  {
    docName: 'Category',
    docType: 'CAT',
    page: 'crud',
    isolationType: 'org',
    documentDate: '',
    docNumber: false,
  },

  {
    docName: 'Customer',
    docType: 'CUST',
    page: 'crud',
    isolationType: 'org',
    documentDate: '',
    docNumber: true,
  },

  {
    docName: 'Invoice',
    docType: 'INV',
    page: 'crud',
    isolationType: 'org',
    documentDate: 'invoiceDate',
    docNumber: true,
  },

  {
    docName: 'Product',
    docType: 'PRD',
    page: 'crud',
    isolationType: 'org',
    documentDate: '',
    docNumber: false,
  },

  {
    docName: 'User',
    docType: 'USER',
    page: 'crud',
    isolationType: 'tenant',
    documentDate: '',
    docNumber: false,
  },
];
