/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
export const foreignkeys = {
  user: { tenant: ['owner._id'], permission: ['userId'] },
  organization: { branch: ['organization._id'] },
  branch: { docnoformat: ['branch._id'] },
  docnoformat: { customer: ['docNoFormat._id'], invoice: ['docNoFormat._id'] },
  customer: { invoice: ['customer._id'] },
  product: { invoicedetails: ['product._id'] },
  category: { product: ['category._id'] },
};
