/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { Schema } from 'mongoose';
import {  Category,  }  from '../types/cat.type';
const schemasetting = {
  
      
    
          _id: {type:'string', required:true},  //force _id as string
          
    
          created: {type: String, required: false},  //field 
          
    
          updated: {type: String, required: false},  //field 
          
    
          createdBy: {type: String, required: false},  //field 
          
    
          updatedBy: {type: String, required: false},  //field 
          
    
          tenantId: {type: Number, required: false},  //field 
          
    
          orgId: {type: Number, required: false},  //field 
          
    
          branchId: {type: Number, required: false},  //field 
          
    
          categoryCode: {type: String, required: true},  //field 
          
    
          categoryName: {type: String, required: true},  //field 
          
    
          active: {type: Boolean, required: false},  //field 
          
    
          categoryType: {type: String, required: false},  //field 
          
    
          description: {type: String, required: false},  //field 
      };

export const CategoryMongoSchema = new Schema(schemasetting,{collection: 'category'})
.pre('save', function(next) {
    this.increment();
    return next();
})

     
       
            .index({ 'orgId':1, 'categoryCode': 1 }, { unique: true })
      
  
  


  