/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2024-02-23
 * Author: Ks Tan
 */
import { Schema } from 'mongoose';
import { Organization } from '../types/org.type';
const schemasetting = {
  _id: { type: 'string', required: true }, //force _id as string

  created: { type: String, required: false }, //field

  updated: { type: String, required: false }, //field

  createdBy: { type: String, required: false }, //field

  updatedBy: { type: String, required: false }, //field

  tenantId: { type: Number, required: false }, //field

  orgId: { type: Number, required: false }, //field

  branchId: { type: Number, required: false }, //field

  orgCode: { type: String, required: true }, //field

  orgName: { type: String, required: true }, //field

  active: { type: Boolean, required: false }, //field

  description: { type: String, required: false }, //field

  timeZone: { type: String, required: false }, //field

  offsetMinute: { type: Number, required: false }, //field

  currency: { type: String, required: false }, //field

  country: { type: String, required: false }, //field
};

export const OrganizationMongoSchema = new Schema(schemasetting, {
  collection: 'organization',
})
  .pre('save', function (next) {
    this.increment();
    return next();
  })

  .index({ tenantId: 1, orgCode: 1 }, { unique: true })

  .index(
    {
      orgId: 1,
    },
    { unique: true },
  );
