/**
 * This file was automatically generated by simpleapp generator during initialization. It is changable.
 * --remove-this-line-to-prevent-override--
 * last change 2024-02-22
 * author: Ks Tan
 */
export type ForeignKey = {
    _id: string
    code?:string
    label: string
    [key:string]:any
  };

export type UserPermission = {
  permId: string;
  branchId: number
  branch: ForeignKey
  groups: string[]
  userId : string
}
